import type { Metadata } from "next";
import { JetBrains_Mono } from "next/font/google";
import { Vortex } from "@/components/ui/vortex";
import MusicPlayer from "@/components/global/music-player";
import "./globals.css";

const inter = JetBrains_Mono({ variable: "--jetbrains_mono", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "xTris",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Vortex
          baseSpeed={0.4}
          rangeSpeed={1}
          baseHue={250}
          rangeY={250}
          particleCount={80}
          backgroundColor="#050505"
          className="w-full h-full z-0"
        >
          {children}
          <MusicPlayer className="fixed right-8 bottom-8 z-99" />
        </Vortex>
      </body>
    </html>
  );
}
